### ISSUE TITLE
Getting this error quite frequently: "Twitter weird response."

### ISSUE THREAD

**Issue by jackyarora** [Jefferson-Henrique/GetOldTweets-python#15]
command executing

python Exporter.py --querysearch '@realDonaldTrump' --since 2016-06-11 --until 2016-06-18 --maxtweets 10000000

Twitter weird response. Try to see on browser: https://twitter.com/search?q=%20since%3A2016-06-11%20until%3A2016-06-18%20%27%40realDonaldTrump%27&src=typd

Done. Output file generated "output_got.csv".

**Comment by Jefferson-Henrique** [comment]
Did you try it again? I can download with no problems, maybe it is some ISP issue.

**Comment by zhutourou** [comment]
I also got this problem a lot and end up getting tweets less than one day.
 
Exporter.py --querysearch 'facebook' --since 2015-01-01 --until 2015-01-15 --maxtweets 0

Twitter weird response. Try to see on browser: https://twitter.com/search?q=%20since%3A2015-01-01%20until%3A2015-01-15%20%27facebook%27&src=typd
Done. Output file generated "output_got.csv".

**Comment by ksk438** [comment]
Also getting this issue. any fix?

**Comment by Sindhu-Kiranmai** [comment]
Hey. Any fix to this issue?

**Comment by MatHatter** [comment]
I believe that it is because there is just so many tweets in one day that to download it all would take forever, so I suggest to take a sample size for each day.

**Comment by jihaneaz** [comment]
Hi, I am also getting this issue. I've tried changing the sample size to 100 or less, the date bounds to one day, and different query searches, but I keep getting the issue. Any fix?

**Comment by taneez08** [comment]
Does anyone get a fixation to this ? Does it have any dealing with internet connection/slow speed ?
Waiting for early response.

**Comment by theredviper9** [comment]
I am getting the same error from some time. @Jefferson-Henrique can you please help me with that, i need those tweets badly for my project.

**Comment by Jefferson-Henrique** [comment]
It really seems a ISP issue, I tried here but I always get all the results, can you share the query you are doing?

**Comment by Jefferson-Henrique** [comment]
For example, here a sample of Trump's query
[output_got.txt](https://github.com/Jefferson-Henrique/GetOldTweets-python/files/797314/output_got.txt)

**Comment by JulienLeal** [comment]
I try it:

python Exporter.py --since 2017-09-04 --until 2017-09-07 --querysearch "maratona"

After "More 100 saved on file..."printed 18 times, I see this message:

 Twitter weird response. Try to see on browser: https://twitter.com/search?q=%20maratona%20since%3A2017-09-04%20until%3A2017-09-07&src=typd

And my output_got.csv is empty. 
I test, wich message printed, I open the csv and more 100 rows is saved. When have this error, my csv is empty.
This bug probabilly is because of number of tweets. How can resolve this ?

Thx :)

**Comment by zdw2126062** [comment]
I tried both versions and it turns out that one is good while the other is bad. And the two are really identical with minor differences:

Good one:
python Exporter.py --since 2017-08-26 --until 2017-08-30 --querysearch "trump" --maxtweets 4000

Bad one: 
 python Exporter.py --since 2017-08-26 --until 2017-08-30 --querysearch "trump" --maxtweets 4000

Hopefully these help :)
