### ISSUE TITLE
.setUntil() causes no return

### ISSUE THREAD

**Issue by jmcnab57** [Jefferson-Henrique/GetOldTweets-python#219]
I was not experiencing this issue a couple days ago but as of today having .setUntil() criteria causes the return of an empty list while removing it will return something. The following is the example i used with two separate criteria.Note that directly using the "url" created by the getJsonResponse function in a browser for both criteria will get the JSON just fine containing full data.
```
criteria_one = got3.manager.TweetCriteria().setQuerySearch("bitcoin").setSince(
    "2015-09-10").setMaxTweets(1).setUntil("2015-09-12").setLang("en")
criteria_two = got3.manager.TweetCriteria().setQuerySearch("bitcoin").setSince(
    "2015-01-01").setMaxTweets(1).setLang("en")
tweet_one = got3.manager.TweetManager.getTweets(criteria_one)[0]
tweet_two = got3.manager.TweetManager.getTweets(criteria_two)[0]
```
Looking at the data in the variable dataJson in the getJsonResponse function shows that the "has_more_items" is always false when .setUntil() is present but true when not present.  Additionally the "min-position" is  'cm+55m--'. which is not the typical full string value.
Behavior was the same in the newer fork https://github.com/Mottl/GetOldTweets3/tree/master/GetOldTweets3
Am i missing something obvious? I've been banging my head trying to debug.

**Comment by Mottl** [comment]
Using the new fork:
```
GetOldTweets3 --username "barackobama" --since 2015-09-10 --until 2015-12-31 --maxtweets 10
Downloading tweets...
Saved 10
Done. Output file generated "output_got.csv".
```
10 results as expected.

Can you run `GetOldTweets3` with the `--debug` option and paste the `debug.log` (install the latest GetOldTweets3 beforehand):
```GetOldTweets3 --username "barackobama" --since 2015-09-10 --until 2015-12-31 --maxtweets 10 --debug > debug.log```

**Comment by rickystream94** [comment]
I'm experiencing the same issue since this morning as well.
Specifying the `since`/`until `parameters makes the tool not return any tweets, whereas removing them makes it work as expected.
@Mottl I tried:
`GetOldTweets3 --querysearch "bitcoin" --since 2015-09-10 --until 2015-09-12 --maxtweets 1`
And I had no tweets returned, unlike what happened to you (latest **0.0.4** version installed).

Here's the `debug.log` when I **don't** specify `since`/`until`:
```
/.../anaconda2/envs/py36/bin/GetOldTweets3 --querysearch bitcoin --maxtweets 1 --debug
GetOldTweets3 0.0.4
Downloading tweets...
https://twitter.com/i/search/timeline?f=tweets&q=bitcoin&src=typd&max_position=
Host: twitter.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64)
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: de,en-US;q=0.7,en;q=0.3
X-Requested-With: XMLHttpRequest
Referer: https://twitter.com/i/search/timeline?f=tweets&q=bitcoin&src=typd&max_position=
Connection: keep-alive
{"min_position":"cm+55m-aDsbFIsXIbDDJFsDFJX-aDsbFIssXEFXFDaEsvv","has_more_items":true ...}
---

1 
Done. Output file generated "output_got.csv".
```
And here's the `debug.log` when `since`/`until` **are specified**:
```
/.../anaconda2/envs/py36/bin/GetOldTweets3 --querysearch bitcoin --maxtweets 1 --since 2018-10-20 --until 2010-10-27 --debug
GetOldTweets3 0.0.4
Downloading tweets...
https://twitter.com/i/search/timeline?f=tweets&q=since%3A2018-10-20%20until%3A2010-10-27%20bitcoin&src=typd&max_position=
Host: twitter.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64)
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: de,en-US;q=0.7,en;q=0.3
X-Requested-With: XMLHttpRequest
Referer: https://twitter.com/i/search/timeline?f=tweets&q=since%3A2018-10-20%20until%3A2010-10-27%20bitcoin&src=typd&max_position=
Connection: keep-alive
{"min_position":"cm+55m--","has_more_items":false,"items_html":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n","new_latent_count":0,"focused_refresh_interval":30000}
---


Done. Output file generated "output_got.csv".
```

**Comment by Mottl** [comment]
@rickystream94, `--until` must be later than `--since` :)
Look again at your command line:
```GetOldTweets3 --querysearch bitcoin --maxtweets 1 --since 2018-10-20 --until 2010-10-27```

Changing `2010-10-27` to `2018-10-27` fixes the behaviour. Please try with correct dates.

**Comment by jmcnab57** [comment]
@rickystream94 You beat me to it. Thanks for posting your logs! @Mottl hope that helps a bit.

With `until `the url generated is [url](https://twitter.com/i/search/timeline?f=tweets&q=since%3A2015-09-10%20until%3A2015-09-12%20bitcoin&src=typd&lang=en&max_position=). If you directly go to the url the retrieved json file it is not the same as the `dataJson `in term of the `"has_more_items"`,`"items_html" `and `"min_position"` not being the correct values. As opposed to removing the until and everything matches up both directly at the [url](https://twitter.com/i/search/timeline?f=tweets&q=since%3A2015-01-01%20bitcoin&src=typd&lang=en&max_position=) as well as at the `dataJson `variable.

I imagine something is going funky at this point in the code but I haven't dove into the functionality of urrlib's OpenerDirector and Base Handlers.
```
opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cookieJar))
opener.addheaders = headers
...
response = opener.open(url)
jsonResponse = response.read()
```

**Comment by jmcnab57** [comment]
> @rickystream94, `--until` must be later than `--since` :)
> Look again at your command line:
> `GetOldTweets3 --querysearch bitcoin --maxtweets 1 --since 2018-10-20 --until 2010-10-27`
> 
> Changing `2010-10-27` to `2018-10-27` fixes the behaviour. Please try with correct dates.

@Mottl thought I see that mistake in ricky's code in my original test example my until and since dates are correct.

**Comment by Mottl** [comment]
@jmcnab57, post here your log please with `--until`.

**Comment by rickystream94** [comment]
> @rickystream94, `--until` must be later than `--since` :)
> Look again at your command line:
> `GetOldTweets3 --querysearch bitcoin --maxtweets 1 --since 2018-10-20 --until 2010-10-27`
> 
> Changing `2010-10-27` to `2018-10-27` fixes the behaviour. Please try with correct dates.

Lol... this was definitely a typo 🤣 
However, when I tried to repro your first command
`GetOldTweets3 --querysearch "bitcoin" --since 2015-09-10 --until 2015-09-12 --maxtweets 1` 
the dates were correct, and still no tweets returned.

A weird thing I've noticed when I fixed the wrong date in my first answer:
1) As I said already, `GetOldTweets3 --querysearch "bitcoin" --since 2015-09-10 --until 2015-09-12 --maxtweets 1` returns 0 tweets.
2) `GetOldTweets3 --querysearch "bitcoin" --since 2015-09-10 --maxtweets 1` returns 1 tweet;
3) `GetOldTweets3 --querysearch bitcoin --maxtweets 1 --since 2018-10-20 --until 2018-10-27` (notice that `until` parameter was specified and that the dates are more recent then in the previous attempts) _**does return**_ 1 tweet.
By tweaking the `until` value, as of today October 31st 2018, it correctly returns 1 tweet when `until` is later or equal October 22nd 2018.

What I can infer from this, is that `until` apparently misbehaves when trying to download tweets that are at least 10 days old.

> @jmcnab57, post here your log please with `--until` and without:
> 
> ```
> GetOldTweets3 --querysearch "bitcoin" --since 2015-09-10 --until 2015-09-12 --maxtweets 1 --debug > debug-until.log
> GetOldTweets3 --querysearch "bitcoin" --since 2015-09-10 --maxtweets 1 --debug > debug_wo.log
> ```

I edited my previous answer with the updated logs, and for sake of completeness I've included also the debug log for the case (3) where the `until` is specified and download works, for recent tweets.

**Comment by Mottl** [comment]
@rickystream94

I've used exactly your urls and can't reproduce the error. Possibly, it could, somehow, be correlated with your previous activity and/or HTTP headers.

Please update GetOldTweets3 to the latest commits and check whether the error is gone. Thanks.
(`pip install -U git+https://github.com/Mottl/GetOldTweets3.git#egg=GetOldTweets3`)

**Comment by rickystream94** [comment]
@Mottl I already had the latest version.
I fixed this by changing my current header option `User-Agent` in `TweetManager.py` from `Mozilla/5.0 (Windows NT 6.1; Win64; x64)` to `Chrome/66.0.3359.181`.
Now everything works as before!

Since it's not the first time that I had to change this value (I had already switched previously from Chrome to Mozilla) I'm just wondering whether it's just fine to switch back & forth between these 2 values when issues like these occur... Is it maybe because of some kind of blocking from Twitter?

**Comment by Mottl** [comment]
@rickystream94 

> I already had the latest version.

I've pushed 2 more commits an hour ago. Just check them.

> Is it maybe because of some kind of blocking from Twitter?

Possibly. Some people said the new UA helps. I will add random choice of `User-Agent` soon.

**Comment by Mottl** [comment]
@jmcnab57, is the latest commits (https://github.com/Mottl/GetOldTweets3/commit/468c03cf6ce06bc5e64062d8f94cbe6d4fb3c71d, https://github.com/Mottl/GetOldTweets3/commit/26b0f00b2a4a3250d7c8e36aa170dee7c0bfd843) on GetOldTweets3 helps?

**Comment by Mottl** [comment]
@jmcnab57 @rickystream94
GetOldTweets3 **0.0.5** adds a random selection of a User-Agent header.
Upgrade with
```pip install -U GetOldTweets3```
