### ISSUE TITLE
Most of the tweets are missing

### ISSUE THREAD

**Issue by ogencoglu** [Jefferson-Henrique/GetOldTweets-python#26]
Hi,

Unfortunately, most of the tweets are missing with query search even though "allTweets=True". I have verified this with several sources (Twitter API, from the Twitter itself from the browser). 

Any ideas why?

**Comment by zhutourou** [comment]
Hi ogencoglu,

I found the same problem before but when I search in twitter.com, it can not also be found. When I search "IBM, start=2016-01-01, end=2016-01-31"  it always stops in some breakpoints. I think it is the problem of twitter database.

**Comment by Jefferson-Henrique** [comment]
Thanks @zhutourou. @ogencoglu some tweets are not indexed by Twitter and you can see for example on a person's timeline but not on search results. All content that you see when you search from the browser should be returned by GOT, you could see different results when you verified with other sources or the same tweets were missing?

**Comment by bkaraoez** [comment]
I have the same problem, When I search " --querysearch "tv" --since 2016-01-01 --until 2016-04-30" it stops. Then I try with shorter ranges, but still it stops before ending date.

As example; when starts at 2016-04-01, ends at 2016-04-30 and I found that there are some missing tweets in 2016-04-13.
"since 2016-04-01 --until 2016-04-12" and "since 2016-04-14 --until 2016-04-30" work fine.
2016-04-13 is missing, although is appears on Twitter search results. 

What should I do?
