### ISSUE TITLE
do we get retweets as well ?

### ISSUE THREAD

**Issue by swatisaoji1** [Jefferson-Henrique/GetOldTweets-python#32]
@Jefferson-Henrique Does this search give Retweets by the user  or just the original tweets ?

**Comment by peterblair** [comment]
Hi @Jefferson-Henrique  and @swatisaoji1 ,  

Jefferson, thanks very much for doing this wonderful project - it is so helpful!

I have found that you only get original tweets and no retweets with this search. Just thought I would add something to this question to say that I have edited the Exporter script slightly in order to get retweets. There is a hidden argument for the Twitter advanced search - if you include " filter:nativeretweets" you get only retweets and if you include " -filter:nativeretweets" you get no retweets. 

I have therefore added a few lines of code to both Exporter.py and TweetManager.py such that, if the user inputs --retweetsinclude, the search runs first for non retweets and then subsequently for only retweets. @Jefferson-Henrique, if you would be interested in including this option then please let me know and I can help out

**Comment by swatisaoji1** [comment]
@peterblair Thats great info , I am curious how did you find it out. ?

**Comment by peterblair** [comment]
Just google!

**Comment by stanupab** [comment]
I used the command below to get only retweets by a specific user;

python Exporter.py --querysearch "from:@username filter:nativeretweets"

**Comment by Spazzolino** [comment]
Hi, I used the query as suggested by @stanupab : the url seems to work fine (I paste and copy it on the browser and the result is as desired), but still GOT doesn't recover the tweets. Am I missing somenthing?

**Comment by amsolis** [comment]
Unfortunately for me the python script is having all kinds of issues. However the Java script works just fine. Is there an option to get the retweets in the Java script?

**Comment by kiemma** [comment]
Hi @peterblair, I'm really interested in retweet data and am wondering if @Jefferson-Henrique ever incorporated your code? I'm super new to coding so I'm not sure how to go about adding that functionality myself. Thanks!!

**Comment by caryshin** [comment]
@peterblair I'm doing a project on this and would like to get retweets included. If you could specify which lines of code you altered, or post files or something, I would greatly appreciate it!

**Comment by wuqui** [comment]
Hello everyone, @peterblair and @caryshin and @stanupab in particular,

I also desperately need retweets in addition to original tweets. This issue was closed, but: is there a feasible solution out there now that (still) works?

I'm querying by search terms, so would `python ... --querysearch "queryword filter:nativeretweets"` do the job?

**Comment by caryshin** [comment]
@wuqui I would try doing that, but I think what I figured out was that retweets are already included but without the RT @ handle. I remember realizing that i had a lot of repeat tweets anyways. Also, since retweets have the same text, you might be able to just use the number of retweets for each tweet instead of actually getting those tweets. Hope this helps.

**Comment by wuqui** [comment]
@caryshin Thanks for your quick reply! 

From looking at the tweets I crawled, I don't really think retweets are included. It's true that some tweets' text is in the data multiple times, but only relatively few copies. In the one dataset I just checked, the top tweet was retweetet about 4,000 times, but there are less than 10 copies in the data sheet.

But it's true that one can simply use the retweet count if one wants to factor in retweets in the analysis as this data is provided in the sheet. That's probably the most elegant solution anyway. Thanks a lot!

**Comment by caryshin** [comment]
@wuqui it doesn't show all 4000 retweets of the original tweets bc it only gets a random 1% sample of tweets. It's entirely possible to get a couple of the retweets but not the original tweet. There definitely are retweets included tho, they just don't always have the handle in the text for some reason..

**Comment by elDudarino** [comment]
@peterblair 

Hey Peter, thanks **so much** for posting your reply!! I am also in need of the retweets and I tried changing the code but for the life of me, I could not! 

**Would you be able to share the specific modifications you did to the code on TweetManager.py and an example call to the script including --retweetsinclude??**

->> "I have therefore added a few lines of code to both Exporter.py and TweetManager.py such that, if the user inputs --retweetsinclude, the search runs first for non retweets and then subsequently for only retweets." <--

I've spent over 20 hours on this, you help would be extremely appreciated! You can reach me at fernando@brandlift.ca if that's easier. Thanks a million, Peter.



> Hi @Jefferson-Henrique and @swatisaoji1 ,
> 
> Jefferson, thanks very much for doing this wonderful project - it is so helpful!
> 
> I have found that you only get original tweets and no retweets with this search. Just thought I would add something to this question to say that I have edited the Exporter script slightly in order to get retweets. There is a hidden argument for the Twitter advanced search - if you include " filter:nativeretweets" you get only retweets and if you include " -filter:nativeretweets" you get no retweets.
> 
> I have therefore added a few lines of code to both Exporter.py and TweetManager.py such that, if the user inputs --retweetsinclude, the search runs first for non retweets and then subsequently for only retweets. @Jefferson-Henrique, if you would be interested in including this option then please let me know and I can help out

**Comment by elDudarino** [comment]
Hey @wuqui , did you get this figured out? I am hurting here, lol! Went through the code and made a few edits but could not get it work... **Were you able to ever come up with a solution to this that you could share?**

**Comment by wuqui** [comment]
Hey, unfortunately not, no. I'd still be interested and glad if you could post it here if you find something!

**Comment by elDudarino** [comment]
Thanks @wuqui! @peterblair Peter, we need you, man! I'll buy you a beer!! Really need some help with this! Thanks everyone.

**Comment by elDudarino** [comment]
Hey @caryshin, were you ever able to figure out exactly which lines to change? Thanks so much.. really appreciate any tips you can offer to get the retweets

**Comment by peterblair** [comment]
Hi, really sorry but this was ages ago and I don't think I still have the code! Hopefully some of what I remember will be useful though!

From what I remember, I think it was a pretty trivial change to the code... If I remember right, GetOldTweets uses the advanced search on Twitter, so if you go to...

https://twitter.com/search-advanced?lang=en-gb&lang=en-gb       (i.e. the advanced search)

and then in the top search bar you type
'try this search filter:nativeretweets'

It comes up with only retweets

But if instead you search 
'try this search -filter:nativeretweets'

It comes up with only non-retweets

So wherever in the code the search arguments are pasted together, I think you just need to paste in either filter:nativeretweets to get just retweets or -filter:nativeretweets to filter them out! Then if you want to do both (as I did), then adding in an extra call to the function that does the searching should do it!

Hope that's helpful!

**Comment by elDudarino** [comment]
**THANK YOU** @peterblair I will give this ago. Really appreciate you taking the time to answer, have a great weekend!
